name: Deploy to Registry

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12
      - name: Install Code Dependencies
        run: |
          make setup
      - name: Unit testing via Pytest (temporarily disabled)
        run: make test || exit 0
  push-to-registry:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u yasir-khalid -p ${{ secrets.GHCR }}
      - name: Build & Push the image
        run: |
          make build-docker-image
          make push-image-to-repository
  deploy-to-cloud:
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook / Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOYMENT_WEBHOOK }}
